# This is a basic workflow to help you get started with Actions

name: My First Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set branch and short commit SHA variables
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image with branch and commit SHA tag
        run: |
          docker build -t hello-world-nginx:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }} .
          docker images

      - name: Run Docker container with tagged image
        run: |
          docker run -d -p 8080:80 --name hello-world-nginx-container hello-world-nginx:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}
          docker ps
